name: state_inference
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.11.5
  - pytorch
  - torchvision
  - pip
  - pip:
    - tqdm
    - notebook
    - seaborn
    - scikit-learn
    - stable-baselines3[extra]
    - ipywidgets
    - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rlwhic