name: state_inference
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.10.13
  - pytorch
  - torchvision
  - scikit-learn
  - tqdm
  - seaborn
  - notebook
  - pip
  - pip:
    - stable-baselines3
    - ipywidgets
    - rich
