name: state_inference
channels:
  - defaults
  - pytorch
dependencies:
  - python>=3.11
  - pytorch
  - torchvision
  - pip
  - pip:
    - tqdm
    - notebook
    - seaborn
    - scikit-learn
    - stable-baselines3[extra]
    - ipywidgets