vae_model_class: StateVae

value_iteration_kwargs:
  gamma: 0.99
  n_iter: 1000
  softmax_gain: 1.0
  epsilon: 0.05
  batch_length: None

q_learning_kwargs:
  alpha: 0.05

state_inference_model:
  set_action:
    - 0
    - 1
    - 2
    - 3
  batch_size: 16
  n_epochs: 20
  grad_clip: True
  optim_kwargs:
    lr: 0.0003