vae_model_class: StateVae
n_train_steps: 30000
n_batches: 12

value_iteration_kwargs:
  gamma: 0.9
  n_iter: 1000
  softmax_gain: 1.0
  epsilon: 0.05
  batch_length: None


state_inference_model:
  batch_size: 64  # matched to PPO
  n_epochs: 10 # matched to PPO
  grad_clip: 1.0
  n_steps: 2048 # matched to PPO
  persistant_optim: True