mlp_vae:
  vae_kwargs:
    z_dim: 16
    z_layers: 8
    beta: 1.0
    tau: 0.5
    tau_annealing_rate: 0.9997 
  encoder_class: MlpEncoder
  decoder_class: MlpDecoder
  encoder_kwargs:
    hidden_sizes:
      - 820
      - 410

  decoder_kwargs:
    hidden_sizes:
      - 410
      - 820

cnn_vae:
  vae_kwargs:
    z_dim: 8
    z_layers: 8
    beta: 1.0
    tau: 0.05
    tau_annealing_rate: 0.85
  encoder_class: CnnEncoder
  decoder_class: CnnDecoder
  encoder_kwargs:
    in_channels: 1
    channels:
      - 32
      - 64
      - 64
    kernel_sizes:
      - 8
      - 4
      - 3
    strides:
      - 4
      - 2
      - 1
  decoder_kwargs:
    output_channels: 1
